import { saveState } from "./persistence.js";
const EVENTS=[{id:'meteor',title:'☄️ Mutagenic Meteor',flavor:'A strange object has crashed into your habitat. What will you do?',choices:[{label:'ABSORB',desc:'+5,000 DNA',run:s=>{s.dna+=5000;s.totalDNA+=5000}},{label:'STUDY',desc:'Gain 3 Essence',run:s=>{s.essence+=3;s.totalEssence+=3}},{label:'IGNORE',desc:'2× DNA/sec for 5 minutes',run:s=>{s.boostUntil=Math.max(s.boostUntil||0,Date.now()+300000)}}]},{id:'organism',title:'🧫 Unknown Organism',flavor:'A tiny organism approaches your creature. It may be useful... or hungry.',choices:[{label:'ABSORB IT',desc:'+1,500 DNA',run:s=>{s.dna+=1500;s.totalDNA+=1500}},{label:'OBSERVE',desc:'+25% tap DNA for 10 minutes',run:s=>{s.eventTapBoostUntil=Date.now()+600000;s.eventTapBoost=1.25}},{label:'RELEASE',desc:'Leave it alone',run:s=>{}}]},{id:'storm',title:'⚡ Genetic Storm',flavor:'The atmosphere crackles with unstable DNA.',choices:[{label:'CHANNEL IT',desc:'3× DNA/sec for 60 seconds',run:s=>{s.eventDpsBoostUntil=Date.now()+60000;s.eventDpsBoost=3}},{label:'HARVEST',desc:'+10,000 DNA',run:s=>{s.dna+=10000;s.totalDNA+=10000}},{label:'HIDE',desc:'Avoid the storm',run:s=>{}}]},{id:'egg',title:'🥚 Mysterious Egg',flavor:'Something is moving inside. You can risk opening it.',choices:[{label:'HATCH',desc:'+8,000 DNA and rare-mutation luck',run:s=>{s.dna+=8000;s.totalDNA+=8000;s.eventLuck=(s.eventLuck||0)+1}},{label:'STUDY',desc:'+5 Essence',run:s=>{s.essence+=5;s.totalEssence+=5}},{label:'LEAVE IT',desc:'Walk away',run:s=>{}}]}];
let state=null,render=()=>{},toast=()=>{},timer=null;const $=id=>document.getElementById(id);
export function setEventContext(s,r,t){state=s;render=r;toast=t;state.event=Object.assign({cooldownUntil:0,seen:0},state.event||{})}
export function eventModifiers(){const now=Date.now();return{tap:now<(state.eventTapBoostUntil||0)?state.eventTapBoost||1:1,dps:now<(state.eventDpsBoostUntil||0)?state.eventDpsBoost||1:1}}
export function maybeEvent(){const now=Date.now();if(now<(state.event?.cooldownUntil||0)||document.querySelector('.modal.show'))return;if(Math.random()>.002)return;openRandomEvent()}
export function openRandomEvent(){const e=EVENTS[Math.floor(Math.random()*EVENTS.length)],modal=$("eventModal");if(!modal)return;$("eventTitle").textContent=e.title;$("eventFlavor").textContent=e.flavor;$("eventChoices").innerHTML=e.choices.map((c,i)=>`<button class="eventChoice" data-event-choice="${i}"><b>${c.label}</b><span>${c.desc}</span></button>`).join('');modal.classList.add('show');state.event.cooldownUntil=Date.now()+120000;state.event.seen++;saveState(state);timer=setTimeout(()=>{if(modal.classList.contains('show'))closeEvent()},30000);document.querySelectorAll('[data-event-choice]').forEach(b=>b.addEventListener('click',()=>choose(e,Number(b.dataset.eventChoice)),{once:true}))}
function choose(e,i){const c=e.choices[i];if(!c)return;c.run(state);closeEvent();render();toast(`${e.title} • ${c.desc}`)}
function closeEvent(){clearTimeout(timer);$("eventModal")?.classList.remove('show');saveState(state)}
export const EVENTS_DATA=EVENTS;
