import { loadState, saveState } from "./persistence.js";
import { SHOP } from "./data/upgrades.js";
import { MUTATIONS } from "./data/mutations.js";
import { setCreatureState, renderCreature } from "./creature.js";
import { setShopContext, renderShop } from "./shop.js";
import { setEvolutionContext, openEvolution } from "./evolution.js";
const $=id=>document.getElementById(id);let state=loadState(),last=performance.now(),tickAcc=0;const OFFLINE_CAP=8*60*60;let offlineEarned=0,offlineSeconds=0;
const ACHIEVEMENTS=[
{id:"firstTap",name:"First Spark",desc:"Generate your first DNA.",check:s=>s.taps>=1,reward:1},
{id:"firstMutation",name:"Natural Selection",desc:"Unlock your first mutation.",check:s=>Object.keys(s.parts).length>=1,reward:2},
{id:"tenMutations",name:"Diverse Genome",desc:"Discover 10 different mutations.",check:s=>Object.keys(s.parts).length>=10,reward:5},
{id:"millionDNA",name:"Genetic Millionaire",desc:"Generate 1,000,000 lifetime DNA.",check:s=>s.totalDNA>=1e6,reward:10},
{id:"tier10",name:"Specialist",desc:"Reach Tier 10 on any mutation.",check:s=>Object.values(s.parts).some(p=>(p.tier||1)>=10),reward:8},
{id:"mastered",name:"Perfect Specimen",desc:"Fully master any mutation.",check:s=>Object.values(s.parts).some(p=>(p.tier||1)>=25),reward:20},
{id:"synergy",name:"Natural Synergy",desc:"Activate your first mutation synergy.",check:s=>activeSynergies().length>=1,reward:5},
{id:"rebirth",name:"Beyond Evolution",desc:"Perform your first Genetic Ascension.",check:s=>s.rebirths>=1,reward:10},
{id:"fiveRebirths",name:"Cycle of Life",desc:"Perform 5 Genetic Ascensions.",check:s=>s.rebirths>=5,reward:25}
];
function fmt(n){if(!isFinite(n))return "∞";if(n<10)return n.toFixed(2).replace(/0+$/,"").replace(/\.$/,"");const u=["","K","M","B","T","Qa","Qi"];let i=0;while(Math.abs(n)>=1000&&i<u.length-1){n/=1000;i++}return (n>=100?n.toFixed(0):n>=10?n.toFixed(1):n.toFixed(2)).replace(/\.0+$/,"")+u[i]}
const SYNERGIES=[{id:"predator",name:"Predator",parts:["clawed","fangs"],dps:0,tap:.15},{id:"aerialHunter",name:"Aerial Hunter",parts:["wings","compound"],dps:.25,tap:0},{id:"insectoid",name:"Insectoid Colony",parts:["insectoid","antennae"],dps:.20,tap:.10},{id:"armored",name:"Armored Organism",parts:["plates","hooved"],dps:.15,tap:0},{id:"grappler",name:"Grappler",parts:["longArms","prehensile"],dps:0,tap:.20}];
function activeSynergies(){return SYNERGIES.filter(s=>s.parts.every(id=>state.parts[id]))}function partBonus(p){const m=MUTATIONS.find(x=>x.id===p.id);if(!m)return{dps:0,tap:0};const tier=Math.max(1,p.tier||1);return{dps:m.dps*tier,tap:m.tap*tier}}
function totals(){let dps=0,tap=1;for(const p of Object.values(state.parts)){const b=partBonus(p);dps+=b.dps;tap+=b.tap}let pm=1,tm=1;for(const s of SHOP){const l=state.shop[s.id]||0;pm+=l*(s.passive||0);tm+=l*(s.tap||0)}for(const s of activeSynergies()){dps*=1+s.dps;tap*=1+s.tap}dps*=pm;tap*=tm;const p=state.prestige||{};dps*=1+(p.memory||0)*.05;tap*=1+(p.instinct||0)*.05;if(Date.now()<state.boostUntil){dps*=2;tap*=2}return{dps,tap}}
function milestoneValue(){return Math.max(1,state.nextMilestone*(1-(state.shop.metabolism||0)*.03))}function toast(s){const x=$("toast");x.textContent=s;x.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>x.classList.remove("show"),2200)}
function checkAchievements(){for(const a of ACHIEVEMENTS){if(state.achievements[a.id]||!a.check(state))continue;state.achievements[a.id]=Date.now();state.essence+=a.reward;state.totalEssence+=a.reward;toast(`🏆 ${a.name} unlocked! +${a.reward} Essence`);saveState(state)}}
function renderAchievements(){const list=$("achievementList"),count=Object.keys(state.achievements).length;if(!list)return;list.innerHTML=`<div class="achievementSummary">${count}/${ACHIEVEMENTS.length} unlocked • Rewards are permanent Genetic Essence</div>`+ACHIEVEMENTS.map(a=>{const done=!!state.achievements[a.id];return `<div class="achievement ${done?"done":"locked"}"><div class="achievementIcon">${done?"🏆":"?"}</div><div><b>${a.name}</b><p>${a.desc}</p></div><strong>${done?"✓ +"+a.reward:"+"+a.reward+" Essence"}</strong></div>`}).join("")}
function prestigeGain(){const efficiency=1+(state.prestige?.efficiency||0)*.1;return Math.max(0,Math.floor(Math.sqrt(Math.max(0,state.totalDNA)/10000)*efficiency))}
function openPrestige(){const gain=prestigeGain();$("prestigeGain").textContent=fmt(gain)+" Genetic Essence";$("rebirths").textContent=state.rebirths;$("prestigeModal").classList.add("show")}
function rebirth(){const gain=prestigeGain();if(gain<1)return toast("Reach 10K lifetime DNA to rebirth.");state.essence+=gain;state.totalEssence+=gain;state.rebirths++;state.dna=0;state.totalDNA=0;state.taps=0;state.choices=0;state.nextMilestone=50;state.parts={};state.shop={};state.boostUntil=0;state.boostType=null;saveState(state);$("prestigeModal").classList.remove("show");render();checkAchievements();toast("Ascension complete! +"+fmt(gain)+" Genetic Essence")}
function buyPrestige(id,cost){if(state.essence<cost)return toast("Not enough Genetic Essence.");state.essence-=cost;state.prestige[id]=(state.prestige[id]||0)+1;saveState(state);render();openPrestige()}
function render(){const t=totals();$("dna").textContent=fmt(state.dna);$("dps").textContent=fmt(t.dps);const target=milestoneValue(),pct=Math.min(100,state.dna/target*100);$("goalPct").textContent=Math.floor(pct)+"%";$("goalBar").style.width=pct+"%";$("goalLabel").textContent="Next mutation • "+fmt(Math.max(0,target-state.dna))+" DNA";$("parts").innerHTML=Object.values(state.parts).map(p=>`<span class="pill">${MUTATIONS.find(x=>x.id===p.id)?.name||p.id} T${p.tier}</span>`).join("");let syn=$("synergies");if(!syn){syn=document.createElement("div");syn.id="synergies";syn.className="synergies";$("parts").after(syn)}syn.innerHTML=activeSynergies().map(s=>`<div class="synergy"><b>🧬 ${s.name}</b><span>${s.dps?"+"+Math.round(s.dps*100)+"% DNA/sec ":""}${s.tap?"+"+Math.round(s.tap*100)+"% tap DNA":""}</span></div>`).join("");$("essence").textContent=fmt(state.essence);renderCreature();renderShop();renderAchievements()}
function checkMilestone(){if(state.dna>=milestoneValue())setTimeout(openEvolution,100)}function tap(){const t=totals();state.dna+=t.tap;state.totalDNA+=t.tap;state.taps++;checkMilestone();checkAchievements();render();saveState(state)}function tick(now){const dt=Math.min(1,(now-last)/1000);last=now;tickAcc+=dt;const t=totals();if(t.dps>0){state.dna+=t.dps*dt;state.totalDNA+=t.dps*dt}if(tickAcc>.25){tickAcc=0;checkMilestone();checkAchievements();render()}requestAnimationFrame(tick)}
function applyOfflineProgress(){const seen=Number(state.lastSeen)||Date.now(),elapsed=Math.max(0,Math.min(OFFLINE_CAP,(Date.now()-seen)/1000));if(elapsed<5)return;const t=totals();offlineSeconds=Math.floor(elapsed);offlineEarned=t.dps*elapsed;if(offlineEarned>0){state.dna+=offlineEarned;state.totalDNA+=offlineEarned;saveState(state)}}function showOfflineWelcome(){if(offlineEarned<=0)return;const mins=Math.floor(offlineSeconds/60),hours=Math.floor(mins/60),m=mins%60;toast(`Welcome back! ${hours?hours+"h ":""}${m}m away • +${fmt(offlineEarned)} DNA`)}function showRewardedAd(cb){setTimeout(()=>cb?.(),0)}
applyOfflineProgress();setCreatureState(state);setShopContext(state,render,toast);setEvolutionContext(state,render,toast);$("tapBtn").addEventListener("click",tap);$("tapTarget").addEventListener("pointerdown",e=>{e.preventDefault();tap()});$("menuBtn").addEventListener("click",()=>$("shopView").classList.add("show"));$("shopBtn").addEventListener("click",()=>$("shopView").classList.add("show"));$("shopClose").addEventListener("click",()=>$("shopView").classList.remove("show"));$("doubleBtn").addEventListener("click",()=>showRewardedAd(()=>{state.boostUntil=Date.now()+15*60*1000;saveState(state);render();toast("DNA production doubled for 15 minutes!")}));$("prestigeBtn").addEventListener("click",openPrestige);$("prestigeClose").addEventListener("click",()=>$("prestigeModal").classList.remove("show"));$("rebirthBtn").addEventListener("click",rebirth);document.querySelectorAll("[data-prestige]").forEach(b=>b.addEventListener("click",()=>buyPrestige(b.dataset.prestige,Number(b.dataset.cost))));render();checkAchievements();showOfflineWelcome();requestAnimationFrame(tick);