import { SHOP } from "./data/upgrades.js";
import { MUTATIONS } from "./data/mutations.js";
import { saveState } from "./persistence.js";
let state=null,renderUI=()=>{},toast=()=>{};const $=id=>document.getElementById(id);
function fmt(n){if(!isFinite(n))return "∞";if(n<10)return n.toFixed(2).replace(/0+$/,"").replace(/\.$/,"");const u=["","K","M","B","T","Qa","Qi"];let i=0;while(Math.abs(n)>=1000&&i<u.length-1){n/=1000;i++}return (n>=100?n.toFixed(0):n>=10?n.toFixed(1):n.toFixed(2)).replace(/\.0+$/,"")+u[i]}
export function setShopContext(nextState,rerender,showToast){state=nextState;renderUI=rerender;toast=showToast}
function shopCost(s){return s.base*Math.pow(1.15,state.shop[s.id]||0)}
function mutationUpgradeCost(m,tier){return Math.ceil(50*Math.pow(3,Math.max(0,tier-1))*(m.rarity==="uncommon"?1.5:m.rarity==="rare"?3:m.rarity==="epic"?8:1))}
const TREE=[{name:"Foundation",items:["stubby","nubby","spikes","eyes","fangs","shortTail"]},{name:"Predator",items:["clawed","clawedArms","fangs","spikedTail"]},{name:"Aerial",items:["hollow","wings","compound"]},{name:"Insectoid",items:["insectoid","antennae"]},{name:"Armored",items:["plates","hooved"]},{name:"Grappler",items:["longArms","prehensile"]}];
function renderTree(){return `<div class="card"><div class="cardTop"><div><h3>Evolution Paths</h3><p>Build toward specialized creature archetypes. Collected mutations are highlighted.</p></div></div>${TREE.map(b=>`<div class="treeBranch"><strong>${b.name}</strong><div class="treeNodes">${b.items.map(id=>{const m=MUTATIONS.find(x=>x.id===id),p=state.parts[id];return `<span class="treeNode ${p?'owned':''}">${p?'✓ ':''}${m?.name||id}</span>`}).join("")}</div></div>`).join("")}</div>`}
function masteryInfo(p){const tier=p?.tier||1;const level=Math.floor(Math.max(0,tier-1)/5);const next=Math.min(25,(level+1)*5+1);const pct=level>=5?100:Math.min(100,((tier-1)%5)*20);return {level,next,pct}}
function renderCodex(){const base=MUTATIONS.filter(m=>!m.requiresFusion),found=Object.keys(state.parts).filter(id=>base.some(m=>m.id===id)).length;return `<div class="card codex"><div class="cardTop"><div><h3>Genetic Codex</h3><p>${found}/${base.length} base mutations discovered • ${Object.keys(state.fusions||{}).length}/${MUTATIONS.filter(m=>m.requiresFusion).length} fusions</p></div><div class="level">${Math.round(found/base.length*100)}%</div></div><div class="codexGrid">${MUTATIONS.map(m=>{const p=state.parts[m.id],f=state.fusions?.[m.id],x=masteryInfo(p);return `<div class="codexEntry ${p||f?'discovered':'unknown'}"><div class="codexName">${p||f?m.name:'???'}</div><div class="codexMeta">${p||f?m.rarity:'Undiscovered'}${p?` • Tier ${p.tier||1}`:f?' • Fused':''}</div>${p?`<div class="masteryLabel">Mastery ${x.level}${x.level>=5?' • COMPLETE':''}</div><div class="masteryBar"><i style="width:${x.pct}%"></i></div><div class="masteryHint">${x.level>=5?'Fully mastered':`Reach Tier ${x.next} to increase mastery`}</div>`:f?'<div class="masteryHint">Fusion discovered</div>':'<div class="masteryHint">Discover through an evolution event</div>'}</div>`}).join("")}</div></div>`}
function renderFusion(){const recipes=MUTATIONS.filter(m=>m.requiresFusion);return `<div class="card fusionSection"><div class="cardTop"><div><h3>🧪 Mutation Fusion</h3><p>Combine two compatible mutations into a powerful new adaptation. Fusion consumes the ingredients.</p></div></div>${recipes.map(m=>{const made=!!state.fusions?.[m.id],has=m.requiresFusion.every(id=>state.parts[id]);return `<div class="fusionRecipe ${made?'made':''}"><div><strong>${made?'✓ ':''}${m.name}</strong><div class="mutLevel">${m.requiresFusion.map(id=>MUTATIONS.find(x=>x.id===id)?.name||id).join(' + ')}</div><div class="mutBonus">+${fmt(m.dps)} DNA/sec • +${fmt(m.tap)} DNA/tap</div><small>${m.desc}</small></div><button class="buy fusionBuy" data-fusion="${m.id}" ${made||!has?'disabled':''}>${made?'FUSED':has?'FUSE':'Requires both mutations'}</button></div>`}).join("")}</div>`}
function renderMutationUpgrades(){const owned=Object.values(state.parts);if(!owned.length)return `<div class="card"><h3>Mutation Upgrades</h3><p>Unlock mutations through evolution events, then strengthen them individually here.</p></div>`;return `<div class="card mutationSection"><div class="cardTop"><div><h3>Mutation Upgrades</h3><p>Upgrade each adaptation independently.</p></div></div>${owned.map(p=>{const m=MUTATIONS.find(x=>x.id===p.id);if(!m)return "";const tier=p.tier||1,max=25,cost=mutationUpgradeCost(m,tier);return `<div class="mutationUpgrade"><div><strong>${m.name}</strong><div class="mutLevel">Tier ${tier}/${max}</div><div class="mutBonus">+${fmt(m.dps*tier)} DNA/sec • +${fmt(m.tap*tier)} DNA/tap</div></div><button class="buy mutationBuy" data-mutation-upgrade="${m.id}" ${tier>=max||state.dna<cost?'disabled':''}>${tier>=max?'MAXED':'Upgrade • '+fmt(cost)+' DNA'}</button></div>`}).join("")}</div>`}
export function renderShop(){const list=$("shopList");if(!list)return;list.innerHTML=renderTree()+renderCodex()+renderFusion()+renderMutationUpgrades()+SHOP.map(s=>{const l=state.shop[s.id]||0,cost=shopCost(s),locked=s.requires&&!state.parts[s.requires];return `<div class="card"><div class="cardTop"><div><h3>${s.name}</h3><p>${s.desc}</p></div><div class="level">LV ${l}${s.max<Infinity?'/'+s.max:''}</div></div><p style="margin-top:8px;color:#b7c5df">${s.effect}</p><button class="buy" data-shop="${s.id}" ${locked||l>=s.max||state.dna<cost?'disabled':''}>${locked?'Requires Insectoid Legs':l>=s.max?'MAXED':'Buy • '+fmt(cost)+' DNA'}</button></div>`}).join("");document.querySelectorAll('[data-shop]').forEach(b=>b.addEventListener('click',()=>buyShop(b.dataset.shop)));document.querySelectorAll('[data-mutation-upgrade]').forEach(b=>b.addEventListener('click',()=>upgradeMutation(b.dataset.mutationUpgrade)));document.querySelectorAll('[data-fusion]').forEach(b=>b.addEventListener('click',()=>fuseMutation(b.dataset.fusion)))}
function buyShop(id){const s=SHOP.find(x=>x.id===id);if(!s)return;const l=state.shop[id]||0,c=shopCost(s);if(l>=s.max||state.dna<c||(s.requires&&!state.parts[s.requires]))return;state.dna-=c;state.shop[id]=l+1;saveState(state);renderUI();toast(s.name+' upgraded to Lv '+(l+1))}
function upgradeMutation(id){const m=MUTATIONS.find(x=>x.id===id),p=state.parts[id];if(!m||!p)return;const tier=p.tier||1,max=25,cost=mutationUpgradeCost(m,tier);if(tier>=max||state.dna<cost)return;state.dna-=cost;p.tier=tier+1;state.mastery[id]=Math.max(state.mastery[id]||0,p.tier-1);saveState(state);renderUI();toast(m.name+' upgraded to Tier '+p.tier)}
function fuseMutation(id){const m=MUTATIONS.find(x=>x.id===id);if(!m?.requiresFusion||state.fusions?.[id]||!m.requiresFusion.every(x=>state.parts[x]))return;for(const req of m.requiresFusion)delete state.parts[req];state.fusions[id]={id,tier:1,seed:Math.floor(Math.random()*1e9)};state.parts[id]={id,tier:1,seed:Math.floor(Math.random()*1e9)};state.choices++;saveState(state);renderUI();toast('🧬 '+m.name+' created!')}
