import { saveState } from "./persistence.js";
const WORLDS=[{id:'ooze',name:'Primordial Ooze',req:0,mult:1,event:'Life begins in the ancient soup.'},{id:'ocean',name:'Ancient Ocean',req:100000,mult:1.5,event:'Your organism enters a world of predators and currents.'},{id:'forest',name:'Cambrian Forest',req:1000000,mult:2.5,event:'Dense life surrounds your evolving creature.'},{id:'jurassic',name:'Jurassic Wilds',req:10000000,mult:5,event:'Massive predators test your adaptations.'},{id:'wasteland',name:'Mutagenic Wasteland',req:100000000,mult:10,event:'Radiation accelerates evolution.'},{id:'alien',name:'Alien Biosphere',req:1000000000,mult:25,event:'Life here follows rules your genome has never seen.'}];
let state=null,render=()=>{},toast=()=>{};const $=id=>document.getElementById(id);function fmt(n){if(n<1000)return Math.floor(n);const u=['K','M','B','T'];let i=-1;while(n>=1000&&i<u.length-1){n/=1000;i++}return n.toFixed(n>=100?0:1)+u[i]}
export function setWorldContext(s,r,t){state=s;render=r;toast=t;state.world=state.world||{id:'ooze',unlocked:['ooze']};state.world.unlocked=state.world.unlocked||['ooze']}
export function worldMultiplier(){return WORLDS.find(w=>w.id===state.world?.id)?.mult||1}
export function renderWorlds(){const list=$("worldList");if(!list)return;list.innerHTML=WORLDS.map(w=>{const unlocked=state.world.unlocked.includes(w.id),active=state.world.id===w.id;return `<button class="worldCard ${active?'active':''} ${unlocked?'':'locked'}" data-world="${w.id}" ${unlocked?'':'disabled'}><div><b>${w.name}</b><p>${w.event}</p><small>${unlocked?'×'+w.mult+' DNA production':`Unlock at ${fmt(w.req)} lifetime DNA`}</small></div><strong>${active?'CURRENT':unlocked?'ENTER':'🔒'}</strong></button>`}).join('');document.querySelectorAll('[data-world]').forEach(b=>b.addEventListener('click',()=>selectWorld(b.dataset.world),{once:true}))}
export function checkWorldUnlocks(){for(const w of WORLDS){if(state.totalDNA>=w.req&&!state.world.unlocked.includes(w.id)){state.world.unlocked.push(w.id);toast('🌍 New world unlocked: '+w.name);saveState(state)}}}
function selectWorld(id){const w=WORLDS.find(x=>x.id===id);if(!w||!state.world.unlocked.includes(id))return;state.world.id=id;saveState(state);render();renderWorlds();toast('🌍 Entered '+w.name)}
export const WORLD_DATA=WORLDS;
